"""Expert iteration as a cold start for GRPO, in the training process.

`pdd.expert_iter` already does the sampling and the mining, but it does them
against a served model and leaves the fine-tuning to the caller. That split is
right for a CPU host driving an API. It is wrong for a rented GPU, where the
model is already resident with a colocated vLLM engine and the round trip
through a server, a corpus file and a separate SFT script costs an hour of paid
time per round and a second copy of the weights.

So this module runs the loop where the weights are: sample with the engine
already serving the policy, grade with the kernel, mine, fine-tune the same
adapter, repeat. What comes out is a policy with a non-trivial pass rate, which
is the precondition GRPO needs and does not supply for itself.

## Why this comes first

GRPO's update is proportional to the spread of reward inside a rollout group. At
a 0.5% pass rate essentially every group is flat and essentially every update is
zero -- so the run is not slow, it is stationary. Expert iteration has no such
requirement: it needs a success to exist *somewhere in the corpus*, not several
times on one prompt. `expert_iter.mine` sharpens this further by mining
per-target proofs out of failed responses, so a policy that never solves a whole
task still yields training data every round.

This is also the concrete form of the finding that supervised fine-tuning on
verified data beats RL on the same verifier: it does, from a cold start.
Neither replaces the other. The corpus here is generated by the policy and
accepted by the kernel, so what SFT propagates is the verifier's judgement, and
what GRPO adds afterwards is preference between attempts the verifier accepts
and attempts it rejects -- which no supervised objective expresses.

## What is deliberately not done

No reference proof enters the corpus. `expert_iter.mine` uses reference proofs
only as context, to isolate the target under test, and every completion banked
here was sampled from the policy. Distilling the oracle would produce a better
number and a meaningless one.

Held-out theories are never sampled: the sampler is built from the training
split, so the evaluation stays honest across rounds.
"""

from __future__ import annotations

import json
from pathlib import Path

from .expert_iter import run_round
from .replay import ProofBuffer
from .task import Task


def draw_tasks(
    sampler,
    count: int,
    tokenizer,
    max_prompt_tokens: int,
    format_example: bool,
) -> tuple[list[Task], int]:
    """Draw `count` tasks whose prompts fit the context, plus how many did not.

    Oversized prompts are dropped rather than truncated for the same reason
    `train_grpo.build_dataset` drops them: left truncation removes the
    definitions and keeps the goals, producing an unsolvable task that is then
    scored as if it were solvable.
    """
    tasks: list[Task] = []
    oversized = 0
    attempts = 0
    while len(tasks) < count and attempts < count * 20:
        attempts += 1
        task = sampler.sample()
        prompt = task.prompt(format_example=format_example)
        if len(tokenizer(prompt)["input_ids"]) > max_prompt_tokens:
            oversized += 1
            continue
        tasks.append(task)
    return tasks, oversized


def bootstrap(
    model,
    tokenizer,
    sampler,
    grader,
    *,
    completer_factory,
    sft,
    out: Path,
    rounds: int,
    tasks: int,
    samples: int,
    depths: "tuple[int, ...] | None",
    volume: "int | None",
    max_prompt_tokens: int,
    format_example: bool = True,
    buffer: "ProofBuffer | None" = None,
    sft_steps: int = 120,
    sft_lr: float = 1e-5,
    stop_score: float = 0.55,
) -> dict:
    """Run expert iteration until the policy is warm, and report each round.

    `completer_factory(adapter_dir)` returns a callable mapping prompts to
    completions, sampling from the adapter just written. `sft(buffer, steps, lr,
    out_dir)` fine-tunes the live model on the buffer. Both are injected rather
    than imported so this module stays importable without CUDA.

    The buffer accumulates across rounds and is *not* cleared: an early round's
    proofs are still correct proofs, and dropping them would let the policy
    forget lemmas it solved once. Deduplication in `ProofBuffer` is what keeps
    that from collapsing into a corpus of `rfl`.

    Stops early once the mean per-target score clears `stop_score`. Past that
    point the groups GRPO will draw already have spread, and further supervised
    passes only narrow the policy before the RL stage gets to explore.
    """
    sampler.depths = depths
    sampler.volume = volume
    buffer = buffer if buffer is not None else ProofBuffer()
    out.mkdir(parents=True, exist_ok=True)
    records: list[dict] = []

    for rnd in range(rounds):
        print(f"\n--- expert iteration round {rnd} ---")
        # vLLM serves an adapter by path, not from memory, so the current
        # weights have to hit disk before they can be sampled from. Round 0
        # writes the freshly initialised adapter, whose B matrices are zero and
        # which therefore samples exactly as the base model does.
        adapter_dir = out / f"round{rnd}" / "adapter"
        adapter_dir.mkdir(parents=True, exist_ok=True)
        model.save_lora(str(adapter_dir))
        complete = completer_factory(adapter_dir)

        drawn, oversized = draw_tasks(
            sampler, tasks, tokenizer, max_prompt_tokens, format_example
        )
        if not drawn:
            raise SystemExit(
                "every sampled task exceeded the prompt budget; raise "
                "--max-prompt-tokens or lower --ei-depths"
            )
        if oversized:
            print(f"  dropped {oversized} oversized tasks")

        examples, summary = run_round(
            complete,
            sampler,
            grader,
            tasks=len(drawn),
            samples=samples,
            format_example=format_example,
            drawn=drawn,
        )
        fresh = buffer.extend(examples)
        summary.update({"round": rnd, "fresh": fresh, "banked": len(buffer),
                        "oversized": oversized})

        print(f"  rollouts     {summary['rollouts']}")
        print(f"  solved tasks {summary['solved_tasks']}")
        print(f"  mean score   {summary['mean_score']:.3f}")
        print(f"  mined        {summary['examples']} "
              f"({summary['whole']} whole, {summary['target']} per-target), "
              f"{fresh} new")
        print(f"  buffer       {buffer.summary()}")

        if len(buffer) < 32:
            print("  too few verified proofs to fine-tune on; sampling again")
            records.append(summary)
            continue

        record = sft(buffer, sft_steps, sft_lr, out / f"round{rnd}" / "sft")
        summary["sft"] = record
        records.append(summary)
        buffer.save(out / f"round{rnd}" / "verified.jsonl")
        (out / "log.json").write_text(json.dumps(records, indent=2) + "\n")

        if summary["mean_score"] >= stop_score:
            print(f"  score {summary['mean_score']:.3f} clears {stop_score}; "
                  "groups will have spread. Handing over to GRPO.")
            break

    final = out / "adapter"
    final.mkdir(parents=True, exist_ok=True)
    model.save_lora(str(final))
    buffer.save(out / "verified.jsonl")
    (out / "log.json").write_text(json.dumps(records, indent=2) + "\n")
    print(f"\nbootstrap done: {buffer.summary()}")
    return {"rounds": records, "adapter": str(final), "banked": len(buffer)}
