"""Expert iteration: sample, keep what the kernel accepts, fine-tune, repeat.

The bootstrap problem GRPO cannot solve on its own. A group-relative method
learns from differences *within* a group of rollouts sampled from one prompt, so
a prompt the policy never solves contributes nothing however many times it is
attempted. At a 0.5% success rate almost every group is flat, and almost every
update is zero. Expert iteration has no such requirement: it needs successes to
exist *somewhere in the corpus*, not several times on the same prompt.

So this is the cold-start stage. Run it until the policy solves enough that
groups have spread, then switch to `pdd.train_grpo`.

## What counts as an expert trajectory

Two kinds, and the second is the one this environment makes available for free:

1.  **Whole-task successes.** Every target proved. The prompt and the model's
    own response go into the corpus verbatim.

2.  **Per-target successes mined out of partial failures.** A response that
    proved three of four targets contains three correct proofs. Each is
    re-expressed as a single-target task -- the same lemma, withheld alone --
    paired with the block the model actually wrote. This is the reward
    granularity result used as a *data* source rather than as a reward: the
    kernel already computed a per-declaration verdict, and discarding the good
    proofs because they arrived alongside a bad one throws away most of what a
    weak policy produces.

Nothing here trains on reference proofs. Every completion in the output corpus
was generated by the policy and independently accepted by the kernel, so the
usual expert-iteration failure -- distilling the oracle instead of the policy --
cannot occur. Reference proofs are only ever used as *context*, to isolate the
target being checked.

## Held-out theories

Sampling draws from the training split only. `ifc-b3*` is never mined, so the
held-out evaluation in `pdd.evaluate` stays honest across rounds.

Usage:

    # generate a corpus against a served model (CPU host is fine)
    uv run python -m pdd.expert_iter --model <served> --rounds 1 \\
        --tasks 256 --samples 8 --out runs/ei

    # then fine-tune on runs/ei/round0.jsonl with any SFT trainer
"""

from __future__ import annotations

import argparse
import json
import random
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from .env import TaskSampler, all_families, split_families
from .grader import Verdict
from .reward import RewardConfig
from .rollout import Grader, Rollout
from .task import TARGET_MARKER, Task

ROOT = Path(__file__).resolve().parents[2]


@dataclass
class Example:
    """One supervised example, in the chat format every SFT trainer accepts."""

    prompt: str
    completion: str
    #: "whole" or "target" -- which of the two mining routes produced this.
    source: str
    depth: int
    family: str
    targets: int

    def as_row(self) -> dict:
        return {
            "messages": [
                {"role": "user", "content": self.prompt},
                {"role": "assistant", "content": self.completion},
            ],
            "source": self.source,
            "depth": self.depth,
            "family": self.family,
            "targets": self.targets,
        }


def single_target_task(task: Task, target: str) -> Task:
    """The same lemma withheld on its own, everything else supplied.

    This is exactly the file the grader compiled when it issued that target's
    verdict, so the block being paired with this prompt is known to close this
    goal in this context. Re-deriving the task rather than reusing the multi
    target one matters: pairing a single proof with a prompt that asks for four
    would teach the policy to answer three quarters of the question.
    """
    return Task(task.instance, (target,), "compositional")


def mine(rollouts: "list[Rollout]", format_example: bool) -> list[Example]:
    """Turn graded rollouts into supervised examples.

    Deduplicated on (prompt, completion): a policy early in training emits the
    same short proof for the same lemma across many samples, and a corpus that
    counted each one separately would weight the easiest lemmas by however often
    they happened to be sampled.
    """
    seen: set[tuple[str, str]] = set()
    out: list[Example] = []

    for r in rollouts:
        task = r.task
        if r.shaped.binary:
            prompt = task.prompt(format_example=format_example)
            body = "\n".join(
                f"{TARGET_MARKER}{task.instance.names[k]}\n{r.blocks[k].rstrip()}"
                for k in task.ordered_targets
            )
            key = (prompt, body)
            if key not in seen:
                seen.add(key)
                out.append(Example(prompt, body, "whole", task.depth,
                                   task.family.name, task.volume))
            continue

        # Partial credit as training data.
        for target, verdict in r.shaped.per_target.items():
            if verdict != Verdict.PROVED.value:
                continue
            solo = single_target_task(task, target)
            prompt = solo.prompt(format_example=format_example)
            name = task.instance.names[target]
            body = f"{TARGET_MARKER}{name}\n{r.blocks[target].rstrip()}"
            key = (prompt, body)
            if key not in seen:
                seen.add(key)
                out.append(Example(prompt, body, "target",
                                   task.family.depth_of(target),
                                   task.family.name, 1))
    return out


def run_round(
    complete,
    sampler: TaskSampler,
    grader: Grader,
    *,
    tasks: int,
    samples: int,
    format_example: bool,
) -> tuple[list[Example], dict]:
    """Sample, grade, mine. Returns the examples and a summary of the round."""
    drawn = sampler.batch(tasks)
    flat = [t for t in drawn for _ in range(samples)]
    prompts = [t.prompt(format_example=format_example) for t in flat]
    rollouts = grader.grade_batch(flat, complete(prompts))
    examples = mine(rollouts, format_example)

    verdicts: Counter[str] = Counter()
    for r in rollouts:
        verdicts.update(r.shaped.per_target.values())

    summary = {
        "tasks": len(drawn),
        "rollouts": len(rollouts),
        "solved_tasks": sum(1 for r in rollouts if r.shaped.binary),
        "mean_score": sum(r.shaped.score for r in rollouts) / len(rollouts),
        "examples": len(examples),
        "whole": sum(1 for e in examples if e.source == "whole"),
        "target": sum(1 for e in examples if e.source == "target"),
        "verdicts": dict(verdicts),
        "lean_calls": grader.stats.lean_calls,
    }
    return examples, summary


def write_corpus(examples: "list[Example]", path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as fh:
        for ex in examples:
            fh.write(json.dumps(ex.as_row()) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--model", required=True)
    ap.add_argument("--base-url", default="http://localhost:8000/v1")
    ap.add_argument("--out", default=str(ROOT / "runs" / "ei"))
    ap.add_argument("--rounds", type=int, default=1,
                    help="sampling rounds; fine-tuning between rounds is done "
                         "outside this script, then it is re-run against the "
                         "updated server")
    ap.add_argument("--tasks", type=int, default=256,
                    help="distinct tasks sampled per round")
    ap.add_argument("--samples", type=int, default=8,
                    help="rollouts per task; more helps here, since one success "
                         "anywhere is enough to yield an example")
    ap.add_argument("--depths", type=int, nargs="*", default=None)
    ap.add_argument("--volume", type=int, default=3)
    ap.add_argument("--temperature", type=float, default=1.0,
                    help="higher than for measurement on purpose: this stage "
                         "wants coverage, and every sample is kernel-checked")
    ap.add_argument("--max-tokens", type=int, default=768)
    ap.add_argument("--workers", type=int, default=16)
    ap.add_argument("--concurrency", type=int, default=16)
    ap.add_argument("--no-format-example", action="store_true")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    from .policy import LocalPolicy

    train, held_out = split_families(all_families(include_corpus=True))
    print(f"mining: {sorted(train)}")
    print(f"never touched: {sorted(held_out)}")

    sampler = TaskSampler(
        families=train,
        depths=tuple(args.depths) if args.depths else None,
        volume=args.volume or None,
        rng=random.Random(args.seed),
    )
    policy = LocalPolicy(
        model=args.model,
        base_url=args.base_url,
        temperature=args.temperature,
        max_tokens=args.max_tokens,
        concurrency=args.concurrency,
    )
    grader = Grader(workers=args.workers, config=RewardConfig())
    out = Path(args.out)

    for rnd in range(args.rounds):
        print(f"\n=== round {rnd} ===")
        examples, summary = run_round(
            policy.complete_many,
            sampler,
            grader,
            tasks=args.tasks,
            samples=args.samples,
            format_example=not args.no_format_example,
        )
        path = out / f"round{rnd}.jsonl"
        write_corpus(examples, path)
        (out / f"round{rnd}.summary.json").write_text(
            json.dumps(summary, indent=2) + "\n"
        )

        print(f"  rollouts        {summary['rollouts']}")
        print(f"  solved tasks    {summary['solved_tasks']}")
        print(f"  mean score      {summary['mean_score']:.3f}")
        print(f"  examples        {summary['examples']} "
              f"({summary['whole']} whole, {summary['target']} per-target)")
        print(f"  wrote           {path}")
        print(f"  grading         {grader.stats}")

        if not examples:
            print("\n  no accepted proofs. Nothing to fine-tune on. Lower "
                  "--depths, raise --samples or --temperature.")
            break
        if rnd + 1 < args.rounds:
            print("\n  fine-tune on the file above and restart the server "
                  "before the next round.")


if __name__ == "__main__":
    main()
