#!/usr/bin/env bash
# Resume from a banked proof corpus: supervise, measure, then train.
#
#     bash scripts/plan-b.sh                     # on the GPU host
#     CORPUS=/root/verified.jsonl bash scripts/plan-b.sh
#
# The corpus is 3180 Lean proofs generated by a policy and accepted by the
# kernel, mined over four expert-iteration rounds on a rental that then died
# before the policy-gradient stage ran. Every one of them is still accepted:
# the kernel is deterministic and the toolchain is pinned, so acceptance does
# not expire and re-earning them would buy nothing.
#
# Three things about the ordering are deliberate.
#
# **Supervise before measuring.** `--distil-first` fine-tunes on the corpus
# before any stage runs, so the first held-out number describes a policy that
# has already absorbed what expert iteration found.
#
# **Measure before training.** Stage 0 runs zero optimizer steps: it saves the
# adapter and evaluates it. That locks in a reportable result roughly an hour
# in, so a budget cutoff during GRPO still leaves the expert-iteration half of
# the claim measured. The previous run had no such checkpoint and produced no
# held-out number at all.
#
# **Scalar advantages.** `--factored off` is not a preference. Unsloth replaces
# trl's GRPO loss with its own compiled trainer, whose ratio tensor is built at
# a different width than per-token advantages, and the mismatch surfaces as a
# dynamo error at the first optimizer step. Per-target credit is still in the
# reward; only the per-token attribution is given up.

set -euo pipefail
cd "$(dirname "$0")/.."
export PATH="$HOME/.elan/bin:$HOME/.local/bin:$PATH"

CORPUS="${CORPUS:-$HOME/verified.jsonl}"
MODEL="${MODEL:-deepseek-ai/DeepSeek-Prover-V2-7B}"
OUT="${OUT:-runs/planb-$(date +%Y%m%d-%H%M%S)}"
cores() { nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 16; }

[[ -f "$CORPUS" ]] || { echo "no proof corpus at $CORPUS" >&2; exit 1; }
echo "corpus  $CORPUS ($(wc -l < "$CORPUS") proofs)"

# 1024 rather than 768. Across the four expert-iteration rounds the share of
# targets that received no block at all climbed 13% -> 19% -> 22% -> 22% as SFT
# taught longer proofs, which is a three-target response being truncated before
# it finishes. That was a fifth of the reward signal discarded unattempted.
mkdir -p "$OUT"
ARGS=(
  --model "$MODEL" --load-in-4bit
  --out "$OUT" --workers "$(cores)" --split binops
  --resume-buffer "$CORPUS" --distil-first --ei-rounds 0
  --factored off
  --max-seq 10240 --max-prompt-tokens 8192 --max-completion-tokens 1024
  --lora-r 32 --gpu-memory-utilization 0.50
  --group 8 --batch 4 --accum 4 --lr 1e-5 --temperature 1.0
  --beta 0.0 --epsilon 0.2 --epsilon-high 0.28
  --refresh-every 50 --oversample 4 --explore 0.35
  --distil on --distil-steps 120 --distil-lr 1e-5
  --eval-tasks 32 --eval-group 8
  --on-stall rescue --stall-retries 0
  --stages '[
    {"depths": [1, 2], "volume": 3, "steps": 0,   "prompts": 64},
    {"depths": [1, 2], "volume": 3, "steps": 200, "prompts": 512},
    {"depths": [2, 3], "volume": 3, "steps": 200, "prompts": 512}
  ]'
)

if [[ "${DRY:-0}" == "1" ]]; then
  printf 'uv run python -m pdd.train_grpo'; printf ' %q' "${ARGS[@]}"; printf '\n'
  exit 0
fi

LOG="$OUT/train.log"
echo "out     $OUT"
echo "log     $LOG"
nohup uv run python -m pdd.train_grpo "${ARGS[@]}" >"$LOG" 2>&1 &
echo "pid     $!"
echo
echo "follow: tail -f $LOG"
