/- `pdd-extract`: kernel-truth dependency extraction.

   Reads the compiled `Environment` and, for every declaration belonging to the
   target module, records the constants actually referenced by its type and its
   value. Those are the dependencies the kernel itself recorded when it accepted
   the declaration.

   The point of doing it this way is that the previous dependency graph was
   written by hand and four of its fourteen edges were fabricated: lemmas
   declared dependencies their proofs never cite, which inflated reported depths
   and invalidated every depth-indexed measurement from that family. Source-text
   parsing would reproduce exactly that class of error, because a proof can
   mention a name it does not use and can use a name it does not mention. The
   environment cannot be wrong about this. -/
import Lean

open Lean Elab Command

namespace PddExtract

/-- Declarations Lean generates for you. These are never tasks: nobody proves
    `Foo.rec` by hand, and posing one as a goal would measure nothing. They are
    still emitted as *supplied* constants so a task file remains compilable. -/
def isAutoGenerated (n : Name) : Bool :=
  n.isInternal
  || n.hasMacroScopes
  || (`Quot).isPrefixOf n
  || match n with
     | .str _ s =>
         s == "rec" || s == "recOn" || s == "casesOn" || s == "brecOn"
         || s == "below" || s == "ibelow" || s == "binductionOn"
         || s == "noConfusion" || s == "noConfusionType"
         || s == "ndrec" || s == "ndrecOn"
         || s == "toCtorIdx" || s == "ctorIdx"
         || s == "sizeOf" || s == "_sizeOf_inst"
         || s.startsWith "match_" || s.startsWith "proof_"
         || s.startsWith "eq_" || s.startsWith "eq_def"
         || s.startsWith "_" || s.endsWith "_spec"
     | _ => false

/-- Structure projections are supplied, not withheld: they are part of the
    theory's interface rather than a proof obligation. -/
def isProjection (env : Environment) (n : Name) : Bool :=
  match env.getProjectionStructureName? n with
  | some _ => true
  | none   => false

def kindOf : ConstantInfo → String
  | .axiomInfo  _ => "axiom"
  | .defnInfo   _ => "def"
  | .thmInfo    _ => "theorem"
  | .opaqueInfo _ => "opaque"
  | .quotInfo   _ => "quot"
  | .inductInfo _ => "inductive"
  | .ctorInfo   _ => "ctor"
  | .recInfo    _ => "rec"

def usedConstants (ci : ConstantInfo) : Array Name :=
  let fromType := ci.type.getUsedConstants
  match ci.value? with
  | some v => fromType ++ v.getUsedConstants
  | none   => fromType

def esc (s : String) : String :=
  s.foldl (init := "") fun acc c =>
    acc ++ (if c == '"' then "\\\"" else if c == '\\' then "\\\\" else toString c)

def jsonArr (xs : Array Name) : String :=
  "[" ++ String.intercalate ", " (xs.toList.map fun n => "\"" ++ esc n.toString ++ "\"") ++ "]"

/-- Emit the graph for `target`.

    Edges are restricted to declarations of the target module. Everything else
    (core, any library) is recorded separately under `external`, because those
    constants are *supplied* to the policy rather than withheld: a task file has
    to import them to compile at all, so they can never be proof obligations. -/
def run (target : Name) (out : System.FilePath) : CommandElabM Unit := do
  let env ← getEnv
  -- Declarations elaborated in *this* file have no module index. Selecting them
  -- rather than an imported module is deliberate: imported theorem values load
  -- lazily and come back as `none`, so every theorem would look
  -- dependency-free. Locally elaborated declarations always carry their proof.
  let inTarget (n : Name) : Bool := (env.getModuleIdxFor? n).isNone

  let mut entries : Array String := #[]
  let mut nRung : Nat := 0
  let mut nAuto : Nat := 0

  for (name, _stale) in env.constants.toList do
    if !inTarget name then continue
    -- Lean elaborates theorem bodies asynchronously, so the entry sitting in
    -- `env.constants` can still have `value? = none` while the proof is being
    -- realised. `find?` forces it. Reading the map directly silently yields
    -- type-only dependencies, which is indistinguishable from a theorem that
    -- genuinely cites nothing, and would have made every rung look depth 1.
    let some ci := env.find? name | continue
    let auto := isAutoGenerated name || isProjection env name
    if auto then nAuto := nAuto + 1

    let used := usedConstants ci
    let mut internal : Array Name := #[]
    let mut external : Array Name := #[]
    for d in used do
      if d == name then continue
      if inTarget d then
        if !(isAutoGenerated d || isProjection env d) then
          if !internal.contains d then internal := internal.push d
      else
        if !external.contains d then external := external.push d

    let axs ← liftCoreM (Lean.collectAxioms name)

    let isThm := match ci with | .thmInfo _ => true | _ => false
    -- A rung is a theorem the human wrote. Definitions are supplied context;
    -- auto-generated declarations are never tasks.
    let isRung := isThm && !auto
    if isRung then nRung := nRung + 1

    entries := entries.push <|
      "  {\"name\": \"" ++ esc name.toString ++ "\""
      ++ ", \"kind\": \"" ++ kindOf ci ++ "\""
      ++ ", \"module\": \"" ++ esc target.toString ++ "\""
      ++ ", \"isTheorem\": " ++ (if isThm then "true" else "false")
      ++ ", \"autoGenerated\": " ++ (if auto then "true" else "false")
      ++ ", \"isRung\": " ++ (if isRung then "true" else "false")
      ++ ", \"deps\": " ++ jsonArr internal
      ++ ", \"external\": " ++ jsonArr external
      ++ ", \"axioms\": " ++ jsonArr axs
      ++ "}"

  IO.FS.writeFile out ("[\n" ++ String.intercalate ",\n" entries.toList ++ "\n]\n")
  logInfo m!"pdd-extract: {entries.size} declarations, {nRung} rungs, {nAuto} auto-generated -> {out}"

end PddExtract

